### ISSUE TITLE
fix(accessibility): don't use button to stylize a link

### ISSUE THREAD

**Issue by benjavicente** [open-source-uc/web#40]
**Describe el error**

Botón en el HTML que no es un botón (un botón debe tener una acción asociada en la página).
Causa problemas de accesibilidad, como por ejemplo que el cursor mostrado sea incorrecto.

https://github.com/open-source-uc/web/blob/45f753c6193125122ab492235942e7d94992a950/index.html#L250-L252

**Comportamiento esperado**

Que sea un _Anchor_, con el mismo estilo actual (mismas clases del botón):

```html
 <a href="https://discord.gg/VMXCNAvjPW" class="btn btn-primary smooth-btn">
    Ingresar
 </a>
```

**Comment by FarDust** [comment]
Según lighthouse esto no es un problema de accesibilidad, facto al usar tab al momento de utilizar la funcionalidad el link y el botón llevan al mismo destino.

![image](https://user-images.githubusercontent.com/26115793/118065780-8c33a700-b36b-11eb-9e83-3b85015f6903.png)

Pero en si seria buena practica realizar el cambio. cambio el label.

**Comment by benjavicente** [comment]
Tengo entendido que esto no lo prueba lighthouse, y que es como de la categoría del  funcionamiento del _tab_ que se menciona que hay que probar manualmente. Con el botón dentro del anchor, se selecciona el enlace dos veces en vez de una.

**Comment by FarDust** [comment]
Por eso digo que es una buena practica y **deberíamos cambiarlo**, pero en si desde el punto de vista funcional no genera nada indeseado en la web como para considerarlo un bug.

En efecto esta es de las cosas que lighthouse no revisan pues puede ser algo esperado, pero algunos autores de buenas practicas lo consideran una mala practica por lo que describes en la issue.

Para este tipo de link también agregaría el `target="_blank"` para que el link se abra en otra ventana, nose que opinas @benjavicente .

**Comment by benjavicente** [comment]
Sí, con esos cambios debería quedar bien.
