### ISSUE TITLE
Clarificar desde que branch se crean otras branches.

### ISSUE THREAD

**Issue by Dyotson** [open-source-uc/web#46]
**Esta tu feature relacionada a un problema? Por favor describe cual es.**
Hoy me ocurrió que agregando mi nombre a la web, no sabia cual de las dos branches (main y development) habia que usar, vi los contributing guidelines pero no encontre cual debia usar, por la cual me guie la que siempre uso, que es main. 

**Describe la solución que te gustaría**
Se deberia clarificar en el contributing guidelines que branch hay que siempre usar, development, deploy, etc.

**Describe posibles soluciones que consideraste**
Aclarar desde un principio todos los comandos a usar en el contributing guidelines.

**Contexto adicional**
Aiuda.

**Comment by FarDust** [comment]
Como indica la linea 12, el branch donde se deben hacer `pull request`  es `development` por lo cual desde esta misma branch debe nacer el cambio para una nueva feature: https://github.com/open-source-uc/web/blame/main/readme.md#L12

**Comment by FarDust** [comment]
Considerar incluir el detalle que las branches deben ser hijos de `development`

**Comment by chepo92** [comment]
> 
> 
> Considerar incluir el detalle que las branches deben ser hijos de `development`, @agucova que opinas?

Sí, debería explicitarse que la branch para contribuir es development, pero esto tb debería venir de una plantilla standar y convención de nombres para las branches

**Comment by agucova** [comment]
> Considerar incluir el detalle que las branches deben ser hijos de `development`, @agucova que opinas?

De acuerdo,

**Comment by FarDust** [comment]
Resuelta en #47
